username: username
password: password
server: https://matrix.org
errorlog: ErrorLog.md # Name of Text file errors will be logged to
componentspath: Components # Name of folder in same path as bot.py containing component scripts